---
- name: Learning about Template Module
  hosts: planetexpress
  gather_facts: yes

  vars:
     enginetype: darkmatter
     people: "Fry, Lela, Zoidberg"
     stuffincargo: Slurm Cola
     primarymission: Make a delivery of slurm cola to the outer regions of Perci Omicron XII

  tasks:
          - name: build a template
            ## Jinja template
            template:
                    src: template01.j2    ## It is implied that you have a templates folder
                    dest: ~/ship.cfg


